import Head from "next/head";
import ContactUsSection from "../components/sections/contact-us/ContactUsSection";
import OurStorySection from "../components/sections/our-story/OurStorySection";
import WhatWeDoSection from "../components/sections/what-we-do/WhatWeDoSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WhatWeDoSection />
        <OurStorySection />
        <ContactUsSection />
      </main>
    </div>
  );
}
